// Code generated by mockery v2.31.4. DO NOT EDIT.

package service_mocks

import (
	constant "belajar-golang-mock/constant"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateNewCat provides a mock function with given fields: ctx, request
func (_m *Service) CreateNewCat(ctx context.Context, request constant.Request) (int64, error) {
	ret := _m.Called(ctx, request)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, constant.Request) (int64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, constant.Request) int64); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, constant.Request) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllCats provides a mock function with given fields: ctx
func (_m *Service) ListAllCats(ctx context.Context) ([]*constant.Response, error) {
	ret := _m.Called(ctx)

	var r0 []*constant.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*constant.Response, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*constant.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*constant.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
